# Generated by Django 4.1.5 on 2023-01-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-created'], 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='flowerbouquet',
            name='image',
            field=models.ImageField(blank=True, upload_to='flower_bouquets', verbose_name='картинка'),
        ),
        migrations.AddField(
            model_name='flowerbouquet',
            name='event_tags',
            field=models.ManyToManyField(related_name='flower_bouquets', to='flower_shop_app.eventtag'),
        ),
    ]
