# Generated by Django 4.1.5 on 2023-01-18 16:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0002_eventtag_alter_order_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('acceptance_of_rules', models.BooleanField(default=False, verbose_name='согласия с правилами')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата')),
                ('status', models.SmallIntegerField(choices=[(1, 'Обрабатывается'), (2, 'Обработана')], default=1, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'консультация',
                'verbose_name_plural': 'консультации',
                'ordering': ['created', 'status'],
            },
        ),
        migrations.AlterModelOptions(
            name='eventtag',
            options={'verbose_name': 'тег события', 'verbose_name_plural': 'теги событий'},
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['created', 'status'], name='flower_shop_created_416573_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['status'], name='flower_shop_status_3d44c2_idx'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['phone_number'], name='flower_shop_phone_n_be5e23_idx'),
        ),
    ]
