# Generated by Django 4.1.5 on 2023-01-19 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0003_consultationrequest_alter_eventtag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowerbouquet',
            name='height',
            field=models.SmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(20)], verbose_name='высота'),
        ),
        migrations.AddField(
            model_name='flowerbouquet',
            name='width',
            field=models.SmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)], verbose_name='ширина'),
        ),
    ]
