# Generated by Django 4.1.5 on 2023-01-19 20:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0004_flowerbouquet_height_flowerbouquet_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowerBouquetAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='название')),
            ],
            options={
                'verbose_name': 'атрибут букета',
                'verbose_name_plural': 'атрибуты букета',
            },
        ),
        migrations.CreateModel(
            name='FlowerBouquetAttributeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_quantity', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество атрибутов в букете')),
                ('flower_bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_bouquet_attributes', to='flower_shop_app.flowerbouquet', verbose_name='букет')),
                ('flower_bouquet_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_bouquet_attributes', to='flower_shop_app.flowerbouquetattribute', verbose_name='атрибут букета')),
            ],
        ),
        migrations.AddField(
            model_name='flowerbouquet',
            name='attributes',
            field=models.ManyToManyField(related_name='flower_bouquets', through='flower_shop_app.FlowerBouquetAttributeItem', to='flower_shop_app.flowerbouquetattribute', verbose_name='атрибуты букета'),
        ),
    ]
