# Generated by Django 4.1.5 on 2023-01-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0005_flowerbouquetattribute_flowerbouquetattributeitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'элемент заказа', 'verbose_name_plural': 'элементы заказа'},
        ),
    ]
