# Generated by Django 4.1.5 on 2023-01-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0006_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowerbouquetattributeitem',
            options={'verbose_name': 'элемент букета', 'verbose_name_plural': 'элементы букета'},
        ),
        migrations.AlterModelOptions(
            name='flowerbouquetitem',
            options={'verbose_name': 'элемент букета', 'verbose_name_plural': 'элементы букета'},
        ),
    ]
