# Generated by Django 4.1.5 on 2023-01-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0007_alter_flowerbouquetattributeitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flowerbouquetattributeitem',
            old_name='flower_quantity',
            new_name='attribute_quantity',
        ),
    ]
