# Generated by Django 4.1.5 on 2023-01-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_shop_app', '0008_rename_flower_quantity_flowerbouquetattributeitem_attribute_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.SmallIntegerField(choices=[(10, 'C 10:00 до 12:00'), (12, 'C 12:00 до 14:00'), (14, 'C 14:00 до 16:00'), (16, 'C 16:00 до 18:00'), (18, 'C 18:00 до 20:00')], default=None, verbose_name='время доставки'),
        ),
    ]
